name = "vps-monitor-worker"
main = "dist/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "vps-monitor-db"
database_id = "__D1_DATABASE_ID__"

[observability]
enabled = true
logs = { enabled = true }

[vars]
USERNAME = "__ADMIN_USERNAME__"
PASSWORD = "__ADMIN_PASSWORD__"
JWT_SECRET = "__JWT_SECRET__"
